[package]
name = "zk-common"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }
aes = "0.8"
ctr = "0.9"
image = { version = "0.24", default-features = false, features = ["png"] }
zune-jpeg = { version = "0.5", default-features = false }
zune-core = { version = "0.5", default-features = false }
libm = "0.2"
